### ISSUE TITLE
docker-compose cannot login

### ISSUE THREAD

**Issue by william-best** [flipped-aurora/gf-vue-admin#11]
1. version V1.1.1 or master
2. problems:
when using 'docker-compose up -d', login xxxx:8000 ,  there is a 'no user' error
3. why
because docker file did not change ip address (redis/mysql) in config.toml, still 127.0.0.1, gf cannot connect to mysql.

**Comment by SliverHorn** [comment]
> 1. version V1.1.1 or master
> 2. problems:
>    when using 'docker-compose up -d', login xxxx:8000 ,  there is a 'no user' error
> 3. why
>    because docker file did not change ip address (redis/mysql) in config.toml, still 127.0.0.1, gf cannot connect to mysql.

Hello, I have tested, 
- server project can be connected to mysql and redis. 
- The reason why the IP address is not used is because after the address is modified in docker-compose.yaml, the server will not run
- The data will be added by itself after starting mysql

**Comment by SliverHorn** [comment]
![image](https://user-images.githubusercontent.com/45428434/96535741-17145d80-12c5-11eb-82af-4115d225dad3.png)
