### ISSUE TITLE
期待更新

### ISSUE THREAD

**Issue by coooooookie** [flipped-aurora/gf-vue-admin#15]

**Comment by SliverHorn** [comment]
- 目前gf-vue-admin 功能应该不会有啥好加的了，可能就是自动代码这块需要时间调试

**Comment by coooooookie** [comment]
好的,我以为计划任务中,像用户多角色没完成呢!

**Comment by SliverHorn** [comment]
> 好的,我以为计划任务中,像用户多角色没完成呢!

多角色涉及改前端较多，很难提供支持，我只写后端和轻微前端修改

**Comment by SliverHorn** [comment]
用户多角色得看 [gin-vue-admin](https://github.com/flipped-aurora/gin-vue-admin)的支持

**Comment by coooooookie** [comment]
好的
