### ISSUE TITLE
多次编辑角色权限会将casbin_rule表清空

### ISSUE THREAD

**Issue by Idream-now** [flipped-aurora/gf-vue-admin#9]
登录角色超级管理员，编辑测试角色权限，前几次是正常的，多次操作后，登录的用户界面报无权限错误，查看数据库casbin_rule表被清空，仅留有我编辑的测试角色的权限的记录

**Comment by SliverHorn** [comment]
> 登录角色超级管理员，编辑测试角色权限，前几次是正常的，多次操作后，登录的用户界面报无权限错误，查看数据库casbin_rule表被清空，仅留有我编辑的测试角色的权限的记录

你看看控制台的sql是否有什么错误的，你这bug我无法复现的

**Comment by Idream-now** [comment]
ClearCasbin(0, authorityId);
这个方法执行应该将authorityId在casbin_rule表对应的权限删除 但是在我的控制台执行的sql是
2020-09-17 14:21:58.817 [DEBU] [  5 ms] DELETE FROM `casbin_rule` 全表清空后才会插入新的数据

**Comment by SliverHorn** [comment]
> ClearCasbin(0, authorityId);
> 这个方法执行应该将authorityId在casbin_rule表对应的权限删除 但是在我的控制台执行的sql是
> 2020-09-17 14:21:58.817 [DEBU] [ 5 ms] DELETE FROM `casbin_rule` 全表清空后才会插入新的数据

我的是这样的`2020-09-17 14:33:14.979 [DEBU] [  2 ms] DELETE FROM `authority_menu` WHERE `authority_id`='9528'`,并没有问题

**Comment by SliverHorn** [comment]
> ClearCasbin(0, authorityId);
> 这个方法执行应该将authorityId在casbin_rule表对应的权限删除 但是在我的控制台执行的sql是
> 2020-09-17 14:21:58.817 [DEBU] [ 5 ms] DELETE FROM `casbin_rule` 全表清空后才会插入新的数据

好的，我知道bug在哪了，我现在尝试解决

**Comment by SliverHorn** [comment]
gdb-adapter适配器出问题了，短时间可能无法修复，我尽快修复，修复好告诉你，感谢的你的Issues

**Comment by SliverHorn** [comment]
问题已经在master上修复了

**Comment by Idream-now** [comment]
点赞👍
